const fs=require('node:fs'),Module=require('node:module'),assert=require('node:assert/strict'),ts=require('typescript'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
function compile(path,replacements={}){const m=new Module(path,module);m.filename=path;m.paths=module.paths;m.require=name=>replacements[name]||require(name);m._compile(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,path);return m.exports;}
const types=compile('lib/types.ts'),core=compile('lib/server.ts'),make=(format,n)=>({id:'hub3_project_'+n,publicationId:'hub3_pub_abcdefghij'+n,ownerId:'fixture',format,status:'published',title:'파크골프 & <새로운> 이야기 '+n,topic:'파크골프',audience:'독자',tone:'기사체',imageIds:['photo-1'],revision:1,createdAt:'2026-10-04T00:00:00.000Z',updatedAt:'2026-10-04T01:00:00.000Z',content:{title:'파크골프 & <새로운> 이야기 '+n,subtitle:'시니어 건강 이야기',intro:'처음부터 HTML에 보이는 도입부',sections:[{id:'section-0',heading:'안전하게 시작하기',body:'검색 로봇이 읽는 실제 본문',imageId:'photo-1',caption:'파크골프 코스'}],closing:'정리',sources:[],review:'',feeds:types.platforms.map(platform=>({platform,hook:platform+' 제목',body:platform+' 독립 피드 본문',hashtags:['파크골프'],imageId:'photo-1',notes:''}))}});
const list=Array.from({length:14},(_,i)=>make(i%3===0?'article':i%3===1?'ebook':'sns',i));
const pub=compile('lib/publication.ts',{'./server':{publicRecords:async()=>list.map(p=>({p})),publicProject:d=>d.p}});
const preview=compile('app/ContentPreview.tsx',{'../lib/types':types}),detail=compile('app/content/[id]/page.tsx',{'next/navigation':{notFound:()=>{throw new Error('404')}},'../../../lib/server':{publication:async id=>list.find(p=>p.publicationId===id)||null},'../../../lib/publication':pub,'../../../lib/types':types,'../../ContentPreview':preview,'./PrintButton':{default:()=>null}}),home=compile('app/page.tsx',{'../lib/types':types,'../lib/publication':pub,'./PublicAccountLink':compile('app/PublicAccountLink.tsx')});
(async()=>{const html=renderToStaticMarkup(await home.default({searchParams:Promise.resolve({})}));assert.ok(html.includes(list[0].publicationId));assert.ok(html.includes('href="/?page=2"'));assert.ok(!html.includes(list[13].publicationId));const page2=renderToStaticMarkup(await home.default({searchParams:Promise.resolve({page:'2'})}));assert.ok(page2.includes(list[13].publicationId));const article=renderToStaticMarkup(await detail.default({params:Promise.resolve({id:list[0].publicationId})}));assert.ok(article.includes('검색 로봇이 읽는 실제 본문'));assert.ok(article.includes('application/ld+json'));assert.ok(article.includes('함께 읽을 이야기'));assert.equal((await detail.generateMetadata({params:Promise.resolve({id:list[0].publicationId})})).alternates.canonical,pub.publicationUrl(list[0]));const sns=renderToStaticMarkup(await detail.default({params:Promise.resolve({id:list[2].publicationId})}));for(const platform of types.platforms)assert.ok(sns.includes(platform+' 독립 피드 본문'));await assert.rejects(()=>detail.default({params:Promise.resolve({id:'missing'})}),/404/);assert.ok(!pub.jsonLd({title:'</script><script>alert(1)</script>'}).includes('</script>'));
for(const name of ['sitemap.xml','rss.xml','robots.txt']){const route=compile(`app/${name}/route.ts`,{'../../lib/publication':pub});const response=await route.GET();assert.equal(response.status,200);const body=await response.text();assert.ok(body.includes(pub.SITE_ORIGIN));if(name!=='robots.txt'){assert.ok(body.includes(list[13].publicationId));assert.ok(body.includes('&amp;')||name==='sitemap.xml');assert.ok(!body.includes('/studio'));}else{assert.ok(body.includes('Disallow: /studio'));assert.ok(body.includes('Allow: /api/hub/image'));}}
console.log('PASS: SSR webzine pagination and links, article HTML, all four SNS feeds in initial HTML, canonical, missing content 404, safe JSON-LD, dynamic sitemap/RSS, crawler rules');})().catch(e=>{console.error(e);process.exitCode=1});
