const fs=require('node:fs'),Module=require('node:module'),assert=require('node:assert/strict'),ts=require('typescript');
function compile(path,replacements){const m=new Module(path,module);m.filename=path;m.paths=module.paths;m.require=n=>replacements[n]||require(n);m._compile(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,path);return m.exports;}
class AppError extends Error{constructor(message,status=400){super(message);this.status=status;}}
const db=new Map();let version=0,calls=0,pubs=0,failPublish=false,onGenerate;
const server={AppError,config:{project:'fixture'},str:(f,k)=>f?.[k]?.stringValue||'',eq:(key,value)=>({key,value}),query:async(c,filters)=>[...db].filter(([k,d])=>k.startsWith(c+'/')&&filters.every(f=>d.fields[f.key]?.stringValue===f.value)).map(([,d])=>structuredClone(d)),getDoc:async(c,id)=>structuredClone(db.get(c+'/'+id)||null),writeDoc:async(c,id,data,token,rev,create)=>{const key=c+'/'+id,old=db.get(key);if((create&&old)||(rev&&old?.updateTime!==rev))throw new AppError('conflict',409);db.set(key,{name:'documents/'+key,fields:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,{stringValue:String(v)}])),updateTime:'v'+(++version)});},readImage:async id=>id==='photo-1'?{id}:null,generate:async()=>{calls++;if(onGenerate)await onGenerate();return {title:'룩북 기사 '+calls,sections:[],review:'사진 검수'};},decodeProject:d=>JSON.parse(d.fields.projectJson.stringValue),saveProject:async(p,token,rev,create)=>server.writeDoc('contentProjects',p.id,{ownerId:p.ownerId,recordType:'hub3Project',projectJson:JSON.stringify(p)},token,rev,create),publish:async(p,token,rev)=>{if(failPublish)throw new AppError('DB temporary failure',502);pubs++;const updated={...p,status:'published',publicationId:'hub3_pub_'+p.id,revision:p.revision+1};await server.saveProject(updated,token,rev);return updated;}};
const auth=compile('lib/service-auth.ts',{'./server':server}),schedules=compile('lib/schedules.ts',{'./server':server,'./service-auth':auth});
const cron=compile('app/api/cron/[phase]/route.ts',{'../../../../lib/server':server,'../../../../lib/service-auth':{authorizeCron:auth.authorizeCron,serviceToken:async()=> 'service'},'../../../../lib/schedules':schedules});
(async()=>{delete process.env.CRON_SECRET;assert.throws(()=>auth.authorizeCron(new Request('https://fixture')),e=>e.status===503);process.env.CRON_SECRET='test-private-secret';assert.throws(()=>auth.authorizeCron(new Request('https://fixture')),e=>e.status===401);const unauthorized=await cron.GET(new Request('https://fixture'),{params:Promise.resolve({phase:'publish'})});assert.equal(unauthorized.status,401);auth.authorizeCron(new Request('https://fixture',{headers:{authorization:'Bearer test-private-secret'}}));assert.equal(schedules.koreaDate(new Date('2026-10-04T23:40:00Z')),'2026-10-05');
const input={requestId:'hub3_schedule_12345678901234567890',topic:'패션 룩북',imageIds:['photo-1'],enabled:true};await assert.rejects(()=>schedules.saveSchedule(input,'owner','token'),e=>e.status===503);Object.assign(process.env,{GEMINI_API_KEY:'test',FIREBASE_CLIENT_EMAIL:'fixture',FIREBASE_PRIVATE_KEY:'fixture'});let s=await schedules.saveSchedule(input,'owner','token');const retry=await schedules.saveSchedule(input,'owner','token');assert.equal(retry.id,s.id);assert.equal(db.size,1);await assert.rejects(()=>schedules.saveSchedule({id:s.id,revision:s.revision,enabled:false},'other','token'),e=>e.status===403);await assert.rejects(()=>schedules.saveSchedule({id:s.id,revision:'stale',enabled:false},'owner','token'),e=>e.status===409);
let r=await schedules.runSchedules('publish','service',new Date('2026-10-04T23:59:00Z'));assert.ok(r.skipped);assert.equal(calls,0);r=await schedules.runSchedules('prepare','service',new Date('2026-10-04T23:40:00Z'));assert.equal(r.results[0].status,'ready');assert.equal(pubs,0);assert.equal(calls,1);await schedules.runSchedules('prepare','service',new Date('2026-10-04T23:45:00Z'));assert.equal(calls,1);r=await schedules.runSchedules('publish','service',new Date('2026-10-05T00:00:00Z'));assert.equal(r.results[0].status,'published');assert.equal(pubs,1);await schedules.runSchedules('publish','service',new Date('2026-10-05T00:05:00Z'));assert.equal(pubs,1);assert.equal(calls,1);assert.ok([...db.values()].some(d=>d.fields.recordType?.stringValue==='hub3Message'));
failPublish=true;r=await schedules.runSchedules('publish','service',new Date('2026-10-06T00:00:00Z'));assert.equal(r.results[0].status,'failed');const before=calls;failPublish=false;r=await schedules.runSchedules('publish','service',new Date('2026-10-06T00:10:00Z'));assert.equal(r.results[0].status,'published');assert.equal(calls,before,'saved draft must survive failed publication');
onGenerate=async()=>{const d=await server.getDoc('contentProjects',s.id);await schedules.saveSchedule({id:s.id,revision:d.updateTime,enabled:false},'owner','token');};r=await schedules.runSchedules('publish','service',new Date('2026-10-07T00:00:00Z'));assert.equal(r.results[0].status,'ready','pause before commit stops publication');const finalPubs=pubs;await schedules.runSchedules('publish','service',new Date('2026-10-07T00:05:00Z'));assert.equal(pubs,finalPubs);
console.log('PASS: protected cron, missing credentials, Korea day boundary, schedule retry idempotency, owner isolation, revision conflict, prepare + publish once/day, publish fallback, failed publication resumes saved draft, pause during generation, persisted daily report');})().catch(e=>{console.error(e);process.exitCode=1});
