'use client';
import {useState} from 'react';
import {Copy,Download} from 'lucide-react';
import type {Project} from '../lib/types';
import {platforms} from '../lib/types';
export const imageUrl=(id:string)=>`/api/hub/image?id=${encodeURIComponent(id)}`;
export default function ContentPreview({project:p,publicReading=false}:{project:Project;publicReading?:boolean}){const [tab,setTab]=useState('Instagram'),[copied,setCopied]=useState(false);const c=p.content,f=c.feeds.find(x=>x.platform===tab)||c.feeds[0];
 if(p.format==='sns'&&publicReading)return <article className="published-social"><header><span className="eyebrow">SOCIAL STORIES</span><h1>{c.title}</h1><p>{c.subtitle}</p><time dateTime={p.updatedAt}>{new Date(p.updatedAt).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</time></header><div className="published-social-grid">{c.feeds.map(f=><section key={f.platform} className="published-feed"><span className="eyebrow">{f.platform}</span>{f.imageId&&<img src={imageUrl(f.imageId)} alt={f.hook} loading="lazy"/>}<h2>{f.hook}</h2><p>{f.body}</p><div className="hashtags">{f.hashtags.map((t,i)=><span key={i}>#{t.replace(/^#/,'')}</span>)}</div></section>)}</div></article>;
 if(p.format==='sns')return <div className="social-preview"><div className="social-tabs">{platforms.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setCopied(false);}}>{t}</button>)}</div>{f&&<div className="social-layout"><article className="feed-card"><header><span className="feed-avatar">h3</span><div><b>HUB STUDIO 03</b><small>{tab} · 게시물 미리보기</small></div><span>•••</span></header>{f.imageId&&<img src={imageUrl(f.imageId)} alt={f.hook}/>}<div className="feed-copy"><h2>{f.hook}</h2><p>{f.body}</p><div className="hashtags">{f.hashtags.map((t,i)=><span key={i}>#{t.replace(/^#/,'')}</span>)}</div></div></article><aside className="feed-controls"><span className="eyebrow">READY FOR YOUR CHANNEL</span><h2>{tab} 피드</h2><p>{f.notes}</p><span className="character-count">본문 {Array.from(f.body).length}자</span><button className="dark" onClick={async()=>{try{await navigator.clipboard.writeText(`${f.hook}\n\n${f.body}\n\n${f.hashtags.map(t=>'#'+t.replace(/^#/,'')).join(' ')}`);setCopied(true);}catch{setCopied(false);}}}><Copy size={16}/>{copied?'복사 완료':'이 피드 복사'}</button>{f.imageId&&<a className="outlined" href={imageUrl(f.imageId)} download={`${tab}.webp`}><Download size={16}/>사진 다운로드</a>}<small>플랫폼 편집기에서 사진과 원고를 함께 게시하세요. 실제 SNS 계정에 자동 게시되지는 않습니다.</small></aside></div>}</div>;
 return <div className={`document-preview ${p.format}`}>{p.format==='ebook'&&<aside className="book-toc"><span className="eyebrow">CONTENTS</span><h3>목차</h3>{c.sections.map((s,i)=><a key={s.id} href={'#'+s.id}><span>{String(i+1).padStart(2,'0')}</span>{s.heading}</a>)}</aside>}<article className="document-paper"><header className="document-cover"><div className="cover-top"><span>HUB STUDIO 03</span><span>{p.format==='ebook'?'E-BOOK EDITION':'EDITORIAL JOURNAL'}</span></div><div className="cover-copy"><span className="cover-kicker">{p.format==='ebook'?'A GUIDE WORTH KEEPING':'THE EDITORIAL'}</span><h1>{c.title}</h1><p>{c.subtitle}</p></div>{p.imageIds[0]&&<img src={imageUrl(p.imageIds[0])} alt={c.title}/>}<div className="cover-bottom"><span>{p.audience}</span><span>{new Date(p.updatedAt).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</span></div></header><div className="document-content">{c.intro&&<section className="document-intro"><span className="eyebrow">{p.format==='ebook'?'PROLOGUE':'LEAD'}</span><p>{c.intro}</p></section>}{c.sections.map((s,i)=><section className="document-chapter" id={s.id} key={s.id}><div className="chapter-heading"><span>{String(i+1).padStart(2,'0')}</span><h2>{s.heading}</h2></div>{s.body.split(/\n\s*\n/).map((t,j)=><p key={j}>{t}</p>)}{s.imageId&&<figure><img src={imageUrl(s.imageId)} alt={s.caption||s.heading}/>{s.caption&&<figcaption>{s.caption}</figcaption>}</figure>}</section>)}{c.closing&&<div className="document-closing"><h2>{p.format==='ebook'?'마치며':'편집자 노트'}</h2><p>{c.closing}</p></div>}{c.sources.length>0&&<section className="document-sources"><h3>제공된 참고 자료</h3>{c.sources.map((s,i)=><p key={i}>{s}</p>)}<small>사용자 제공 자료입니다. 별도 취재·외부 사실 확인 완료를 뜻하지 않습니다.</small></section>}</div><footer>HUB STUDIO 03 · {c.title}</footer></article></div>;
}
