import {notFound} from 'next/navigation';
import {publication} from '../../../lib/server';
import {publishedProjects,SITE_ORIGIN,publicationUrl,photoUrl,excerpt,jsonLd,contentSchema} from '../../../lib/publication';
import {formats} from '../../../lib/types';
import ContentPreview from '../../ContentPreview';
import PrintButton from './PrintButton';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:any){const {id}=await params,p=await publication(id);if(!p)return {title:'콘텐츠를 찾지 못했습니다',robots:{index:false,follow:false}};return {title:`${p.title} | 허브3 웹진`,description:excerpt(p),alternates:{canonical:publicationUrl(p)},robots:{index:true,follow:true},openGraph:{title:p.title,description:excerpt(p),url:publicationUrl(p),type:'article',locale:'ko_KR',siteName:'허브스튜디오3',publishedTime:p.createdAt,modifiedTime:p.updatedAt},twitter:{card:'summary',title:p.title,description:excerpt(p)}};}
export default async function Page({params}:any){const {id}=await params,p=await publication(id);if(!p)notFound();const all=await publishedProjects(),related=all.filter(x=>x.publicationId!==id).sort((a,b)=>Number(b.format===p.format)-Number(a.format===p.format)).slice(0,3);return <main className="public-reading"><div className="public-actions"><a className="brand" href="/"><span className="brand-symbol">h<span>3</span></span><b>HUB3 WEBZINE</b></a><div><a href="/">웹진 전체 보기</a><PrintButton/></div></div><nav className="reading-breadcrumb" aria-label="현재 위치"><a href="/">허브3 웹진</a><span>/</span><a href={`/?type=${p.format}`}>{formats[p.format].label}</a></nav><ContentPreview project={p} publicReading/>{related.length>0&&<section className="reading-related"><h2>함께 읽을 이야기</h2><div>{related.map(x=><a href={`/content/${x.publicationId}`} key={x.publicationId}>{x.imageIds[0]&&<img src={photoUrl(x.imageIds[0])} alt={x.title} loading="lazy"/>}<small>{formats[x.format].label}</small><h3>{x.title}</h3></a>)}</div></section>}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(contentSchema(p))}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'허브3 웹진',item:SITE_ORIGIN},{'@type':'ListItem',position:2,name:p.title,item:publicationUrl(p)}]})}}/></main>;}
