import {randomUUID} from 'node:crypto';
import type {Project} from './types';
import {AppError,query,eq,str,writeDoc,getDoc,generate,saveProject,decodeProject,publish,readImage} from './server';
import {schedulingReady} from './service-auth';
export type DailySchedule={id:string;ownerId:string;topic:string;instruction:string;audience:string;tone:string;imageIds:string[];enabled:boolean;createdAt:string;updatedAt:string;lastStatus?:string;lastError?:string;lastPublicationId?:string;lastDate?:string};
export const koreaDate=(date=new Date())=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
const collection='contentProjects';
const record=(s:DailySchedule)=>({ownerId:s.ownerId,recordType:'hub3Schedule',sourceSite:'hub3',scheduleJson:JSON.stringify(s),updatedAt:s.updatedAt});
export const decodeSchedule=(d:any):DailySchedule=>JSON.parse(str(d.fields,'scheduleJson'));
export async function listSchedules(uid:string,token:string){return (await query(collection,[eq('ownerId',uid),eq('recordType','hub3Schedule')],token)).map(decodeSchedule).sort((a:DailySchedule,b:DailySchedule)=>b.createdAt.localeCompare(a.createdAt));}
export async function saveSchedule(input:any,uid:string,token:string){let old:any;const id=String(input.id||input.requestId||'hub3_schedule_'+randomUUID());if(!/^hub3_schedule_[A-Za-z0-9_-]{20,80}$/.test(id))throw new AppError('예약 ID가 올바르지 않습니다.');if(input.id){old=await getDoc(collection,id,token);if(!old||str(old.fields,'ownerId')!==uid||str(old.fields,'recordType')!=='hub3Schedule')throw new AppError('본인의 예약만 수정할 수 있습니다.',403);if(input.revision!==old.updateTime)throw new AppError('예약이 다른 곳에서 변경됐습니다. 목록을 새로 불러오세요.',409);}if(!input.id){const existing:any=(await query(collection,[eq('ownerId',uid),eq('recordType','hub3Schedule')],token)).find((d:any)=>d.name.endsWith('/'+id));if(existing)return {...decodeSchedule(existing),revision:existing.updateTime};}const previous=old?decodeSchedule(old):null,now=new Date().toISOString();const s:DailySchedule={...previous,id,ownerId:uid,topic:String(input.topic??previous?.topic??'').trim().slice(0,160),instruction:String(input.instruction??previous?.instruction??'').slice(0,4000),audience:String(input.audience??previous?.audience??'일반 독자').slice(0,160),tone:String(input.tone??previous?.tone??'객관적인 기사체').slice(0,120),imageIds:input.imageIds??previous?.imageIds??[],enabled:input.enabled===true,createdAt:previous?.createdAt||now,updatedAt:now};if(!s.topic||!Array.isArray(s.imageIds)||s.imageIds.length<1||s.imageIds.length>6||s.imageIds.some((x:unknown)=>typeof x!=='string'))throw new AppError('기사 주제와 사진 1~6장을 선택해주세요.');if(s.enabled){if(!schedulingReady())throw new AppError('예약 활성화 전에 Vercel의 Gemini·Firebase 서버 인증·CRON_SECRET을 설정해주세요.',503);if((await listSchedules(uid,token)).filter((x:DailySchedule)=>x.enabled&&x.id!==id).length>=3)throw new AppError('계정당 활성 예약은 최대 3개입니다.');const images=await Promise.all(s.imageIds.map(readImage));if(images.some((x:any)=>!x))throw new AppError('공개 사진을 확인해주세요.',404);}await writeDoc(collection,id,record(s),token,old?.updateTime,!old);const d:any=await getDoc(collection,id,token);return {...s,revision:d.updateTime};}
export async function schedulesWithRevision(uid:string,token:string){return (await query(collection,[eq('ownerId',uid),eq('recordType','hub3Schedule')],token)).map((d:any)=>({...decodeSchedule(d),revision:d.updateTime}));}
export async function runSchedules(phase:'prepare'|'publish',token:string,date=new Date()){if(!process.env.GEMINI_API_KEY)throw new AppError('자동 제작에는 서버 GEMINI_API_KEY가 필요합니다.',503);const day=koreaDate(date),now=date.toISOString(),minute=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(date).replace(':',''));if(phase==='publish'&&minute<900) return {date:day,results:[],skipped:'한국 시간 오전 9시 이전입니다.'};if(phase==='prepare'&&minute<800)return {date:day,results:[],skipped:'한국 시간 준비 시간 이전입니다.'};const docs=await query(collection,[eq('recordType','hub3Schedule')],token),results:any[]=[],started=Date.now();for(const original of docs){if(Date.now()-started>150000){results.push({status:'deferred',reason:'실행 시간 한도'});break;}const current:any=await getDoc(collection,original.name.split('/').pop(),token),s=decodeSchedule(current);if(!s.enabled)continue;const runId=`hub3_daily_${s.id.replace('hub3_schedule_','')}_${day.replaceAll('-','')}`,projectId=`hub3_project_${s.id.replace('hub3_schedule_','')}_${day.replaceAll('-','')}`;let runDoc:any=await getDoc(collection,runId,token),run=runDoc?JSON.parse(str(runDoc.fields,'runJson')):{id:runId,status:'new',date:day,projectId,ownerId:s.ownerId};if(run.status==='published'){results.push({id:s.id,status:'already_published'});continue;}if(run.status==='running'&&Date.now()-Date.parse(run.updatedAt)<360000){results.push({id:s.id,status:'locked'});continue;}if(phase==='prepare'&&run.status==='ready'){results.push({id:s.id,status:'already_prepared'});continue;}run={...run,status:'running',phase,updatedAt:new Date().toISOString()};try{await writeDoc(collection,runId,{ownerId:s.ownerId,recordType:'hub3DailyRun',sourceSite:'hub3',runJson:JSON.stringify(run)},token,runDoc?.updateTime,!runDoc);}catch(e){if(e instanceof AppError&&e.status===409){results.push({id:s.id,status:'locked'});continue;}throw e;}
try{let pd:any=await getDoc(collection,projectId,token);if(!pd){const earlier=await query(collection,[eq('ownerId',s.ownerId),eq('recordType','hub3Project')],token),titles=earlier.map((d:any)=>{try{return decodeProject(d);}catch{return null;}}).filter(Boolean).sort((a:any,b:any)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,20).map((p:any)=>p.title);const content=await generate({format:'article',imageIds:s.imageIds,topic:s.topic,audience:s.audience,tone:s.tone,sources:'',instruction:s.instruction+`\n${day} 발행 예정 원고를 준비합니다.한국어 전문 기사로 쓰세요. 기존 제목과 다른 하위 관점·구성을 선택하세요. 기존 제목: ${JSON.stringify(titles)}. 실시간 검색이나 외부 취재를 했다고 표현하지 마세요. 사진에서 확인한 내용과 의견만 구분하세요. 뉴스·가격·날짜·통계·효능은 제공 자료 없이 단정하지 마세요.`},token);const p:Project={id:projectId,ownerId:s.ownerId,format:'article',status:'draft',title:content.title,topic:s.topic,audience:s.audience,tone:s.tone,instruction:s.instruction,imageIds:s.imageIds,content,revision:1,createdAt:now,updatedAt:now};await saveProject(p,token,undefined,true);pd=await getDoc(collection,projectId,token);}if(phase==='publish'){if(!pd)throw new AppError('준비된 원고가 없습니다. 자동 발행하지 않았습니다.',409);const latest:any=await getDoc(collection,s.id,token);if(!decodeSchedule(latest).enabled){run.status='ready';}else{const p=decodeProject(pd);if(p.ownerId!==s.ownerId)throw new AppError('예약 원고 소유권 불일치',403);const pub=await publish(p,token,pd.updateTime);run.status='published';run.publicationId=pub.publicationId;}}else run.status='ready';run.error='';}catch(e){run.status='failed';run.error=e instanceof Error?e.message:'예약 실행 실패';}
run.updatedAt=new Date().toISOString();const lock:any=await getDoc(collection,runId,token);await writeDoc(collection,runId,{ownerId:s.ownerId,recordType:'hub3DailyRun',sourceSite:'hub3',runJson:JSON.stringify(run)},token,lock.updateTime);const latest:any=await getDoc(collection,s.id,token);const updated={...decodeSchedule(latest),lastStatus:run.status,lastError:run.error||'',lastDate:day,lastPublicationId:run.publicationId||'',updatedAt:run.updatedAt};await writeDoc(collection,s.id,record(updated),token,latest.updateTime);await writeDoc(collection,`hub3_message_${runId}-report`,{ownerId:s.ownerId,recordType:'hub3Message',sourceSite:'hub3',updatedAt:run.updatedAt,messageJson:JSON.stringify({id:runId+'-report',role:'assistant',text:run.status==='published'?`${day} 자동 발행 완료: ${s.topic} · /content/${run.publicationId}`:run.status==='ready'?`${day} 예약 원고를 발행 대기로 저장했습니다.`:`${day} 자동 발행 실패: ${run.error}. 저장된 원고는 보존했습니다.`,projectId,createdAt:run.updatedAt})},token);results.push({id:s.id,status:run.status,error:run.error||''});}return {date:day,results};}
